--
-- Created by IntelliJ IDEA.
-- User: phuongnm
-- Date: 04/09/2017
-- Time: 11:17
-- To change this template use File | Settings | File Templates.
--


--- event type message
TYPE_REMOTE_TAKE_A_PHOTO = "TYPE_REMOTE_TAKE_A_PHOTO"
TYPE_SHOW_THINGS_BOT_SEE = "TYPE_SHOW_THINGS_BOT_SEE"
TYPE_CHECK_THINGS_BOT_SEE = "TYPE_CHECK_THINGS_BOT_SEE"
TYPE_POSITION_BOT_SEE_THING = "TYPE_POSITION_BOT_SEE_THING"
TYPE_COMEBACK_POSITION_BOT_SEE_THING = "TYPE_COMEBACK_POSITION_BOT_SEE_THING"
TYPE_SHOW_MESSAGE = "SHOW_MESSAGE"
